import csv
import os

BASE = os.path.dirname(os.path.abspath(__file__))
extract_csv = os.path.join(BASE, 'aitxt_extract.csv')
translated_csv = os.path.join(BASE, 'aitxt_translated.csv')
output_inc = os.path.join(BASE, 'replace_table.inc')

with open(extract_csv, 'r', encoding='utf-8-sig') as f:
    extract = list(csv.DictReader(f))
with open(translated_csv, 'r', encoding='utf-8-sig') as f:
    translated = list(csv.DictReader(f))

assert len(extract) == len(translated), f'CSV line count mismatch: {len(extract)} vs {len(translated)}'

pairs = []  # (orig_str, repl_str)
for e, t in zip(extract, translated):
    assert e['Offset'] == t['Offset'], f'Offset mismatch: {e["Offset"]} vs {t["Offset"]}'

    orig_text = e['Text']
    repl_text = t['Text']

    # skip control codes
    if orig_text.startswith('\\'):
        continue

    if e['Region'] == '1' and e['Inner'] == '1' and ',' in orig_text:
        # inner=1 (dialogue): split by comma, pair positionally
        o_parts = [p.strip() for p in orig_text.split(',')]
        r_parts = [p.strip() for p in repl_text.split(',')]
        if len(o_parts) != len(r_parts):
            # fall back to full entry
            pairs.append((orig_text, repl_text))
        else:
            for o, r in zip(o_parts, r_parts):
                if o:  # non-empty
                    pairs.append((o, r))
    else:
        # inner=2 or single-word inner=1 or R2: full entry
        pairs.append((orig_text, repl_text))

# deduplicate by original text
seen = {}
deduped = []
for o, r in pairs:
    if o in seen:
        continue
    seen[o] = True
    deduped.append((o, r))

entries = []
for o, r in deduped:
    try:
        orig = o.encode('cp932')
    except UnicodeEncodeError:
        print('WARN: cannot cp932 encode [%s]: %s' % (o, ascii(o[:30])))
        continue
    try:
        repl = r.encode('cp936')
    except UnicodeEncodeError:
        print('WARN: cannot gbk encode [%s]: %s' % (r, ascii(r[:30])))
        continue

    if orig == repl:
        continue
    entries.append((len(orig), orig, repl))

# 按原文字节长度降序
entries.sort(key=lambda x: -x[0])

if not entries:
    print('No replacement entries!')
    exit(1)

# 构建二进制 BLOB
blob = bytearray()
meta = bytearray()

blob_offset = 0
for olen, orig, repl in entries:
    meta += olen.to_bytes(2, 'little')
    meta += len(repl).to_bytes(2, 'little')
    meta += blob_offset.to_bytes(4, 'little')
    blob += orig
    blob += repl
    blob_offset += olen + len(repl)

count = len(entries)
print(f'Replace entries: {count}')
print(f'Blob size: {len(blob)} bytes')
print(f'Meta size: {len(meta)} bytes')
print(f'DLL data size: {len(blob) + len(meta)} bytes')

# 生成 .inc
with open(output_inc, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by generate_replace_table.py. Do not edit.\n')
    f.write('#pragma once\n\n')

    f.write('// Binary blob: [orig_bytes][repl_bytes] per entry\n')
    f.write('static const unsigned char REPL_BLOB[] = {\n')
    # Write blob with 12 bytes per line
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_str},\n')
    f.write('};\n\n')

    f.write('// Metadata: [orig_len:le16][repl_len:le16][blob_offset:le32] per entry\n')
    f.write('static const unsigned char REPL_META[] = {\n')
    for i in range(0, len(meta), 12):
        chunk = meta[i:i + 12]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_str},\n')
    f.write('};\n\n')

    # Sorted by orig_len desc, but we also store the cummulative skip for fast iteration
    f.write(f'static const int REPL_COUNT = {count};\n')

print(f'Generated: {output_inc}')
