import csv
import os

BASE = os.path.dirname(os.path.abspath(__file__))
extract_csv = os.path.join(BASE, 'aitxt_extract.csv')
translated_csv = os.path.join(BASE, 'aitxt_translated.csv')
output_inc = os.path.join(BASE, 'replace_table.inc')

extract = list(csv.DictReader(open(extract_csv, 'r', encoding='utf-8-sig')))
translated = list(csv.DictReader(open(translated_csv, 'r', encoding='utf-8-sig')))

assert len(extract) == len(translated), f'CSV line count mismatch: {len(extract)} vs {len(translated)}'

entries = []
for e, t in zip(extract, translated):
    if t['Type'] == 'ctrl':
        continue
    # 验证偏移对齐
    assert e['Offset'] == t['Offset'], f'Offset mismatch: {e["Offset"]} vs {t["Offset"]}'

    try:
        orig = e['Text'].encode('cp932')
    except UnicodeEncodeError:
        print('WARN: cannot cp932 encode [%s]: %s' % (e['Offset'], ascii(e['Text'][:30])))
        continue
    try:
        repl = t['Text'].encode('cp936')
    except UnicodeEncodeError:
        print('WARN: cannot gbk encode [%s]: %s' % (t['Offset'], ascii(t['Text'][:30])))
        continue

    if orig == repl:
        continue
    entries.append((len(orig), orig, repl))

# 按原文字节长度降序
entries.sort(key=lambda x: -x[0])

if not entries:
    print('No replacement entries!')
    exit(1)

# 构建二进制 BLOB
blob = bytearray()
meta = bytearray()

blob_offset = 0
for olen, orig, repl in entries:
    meta += olen.to_bytes(2, 'little')
    meta += len(repl).to_bytes(2, 'little')
    meta += blob_offset.to_bytes(4, 'little')
    blob += orig
    blob += repl
    blob_offset += olen + len(repl)

count = len(entries)
print(f'Replace entries: {count}')
print(f'Blob size: {len(blob)} bytes')
print(f'Meta size: {len(meta)} bytes')
print(f'DLL data size: {len(blob) + len(meta)} bytes')

# 生成 .inc
with open(output_inc, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by generate_replace_table.py. Do not edit.\n')
    f.write('#pragma once\n\n')

    f.write('// Binary blob: [orig_bytes][repl_bytes] per entry\n')
    f.write('static const unsigned char REPL_BLOB[] = {\n')
    # Write blob with 12 bytes per line
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_str},\n')
    f.write('};\n\n')

    f.write('// Metadata: [orig_len:le16][repl_len:le16][blob_offset:le32] per entry\n')
    f.write('static const unsigned char REPL_META[] = {\n')
    for i in range(0, len(meta), 12):
        chunk = meta[i:i + 12]
        hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
        f.write(f'    {hex_str},\n')
    f.write('};\n\n')

    # Sorted by orig_len desc, but we also store the cummulative skip for fast iteration
    f.write(f'static const int REPL_COUNT = {count};\n')

print(f'Generated: {output_inc}')
